#Documentacion de la api de vacunas

POST http://localhost:8080/api/v1/vacuna
Content-Type: application/json

{
  "tipo": "prevencion",
  "fechaAplicacion": "2025-09-12",
  "mascotaId": "d3609366-715e-4806-b6e9-9c7fb7c08221"
}